# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField()),
            ],
        ),
    ]
